/**
 * Helpers for the Zenodo DOI mapping that CI publishes to
 * `public/schemas/doi-mapping.json`. Each library schema is keyed by its slug
 * (the schema id, i.e. the filename without the `.json` extension).
 *
 * The mapping is generated by `.github/scripts/publish-zenodo.py` and committed
 * back to the repo, so the frontend just fetches the static file.
 */

export interface SchemaDoiEntry {
  concept_doi: string | null;
  version_doi: string | null;
  concept_recid: string | null;
  record_id: string | null;
  zenodo_url: string | null;
  version: string;
  checksum: string;
  updated_at: string;
}

export type SchemaDoiMapping = Record<string, SchemaDoiEntry>;

let cachedMapping: Promise<SchemaDoiMapping> | null = null;

/** Fetch (and cache) the DOI mapping. Returns `{}` if it can't be loaded. */
export const fetchSchemaDoiMapping = (): Promise<SchemaDoiMapping> => {
  if (!cachedMapping) {
    cachedMapping = fetch(`${import.meta.env.BASE_URL}schemas/doi-mapping.json`)
      .then((res) => (res.ok ? res.json() : {}))
      .catch(() => ({}));
  }
  return cachedMapping;
};

/** Look up the DOI entry for a schema slug, or `null` if none is published. */
export const getSchemaDoi = async (slug: string): Promise<SchemaDoiEntry | null> => {
  const mapping = await fetchSchemaDoiMapping();
  const entry = mapping[slug];
  if (!entry || !entry.concept_doi) return null;
  return entry;
};

/** Full doi.org URL for the concept DOI (preferred citation), or null. */
export const doiUrl = (doi: string | null | undefined): string | null =>
  doi ? `https://doi.org/${doi}` : null;
