packages:
  - "packages/*"
  - "apps/*"
allowBuilds:
  cbor-extract: false
  core-js: false
  electron: false
  electron-winstaller: false
  esbuild: true
  onnxruntime-node: true
  sharp: false
  workerd: true
