[package]
name = "greedy-rs-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = ["ssd", "nmi", "parallel", "gzip"]
parallel = ["dep:rayon"]
gzip = ["dep:flate2"]
ssd = []
nmi = []

[dependencies]
rayon = { version = "1", optional = true }
flate2 = { version = "1", default-features = false, features = ["rust_backend"], optional = true }
