[package]
name = "preprocessing"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "=0.2.114"
js-sys = "=0.3.91"
qsm-core = { git = "https://github.com/astewartau/QSM.rs", rev = "3aa02ca2ba77b4cc069366a7db9847d6b0c9d19d" }

[profile.release]
opt-level = 3
lto = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
