#!/usr/bin/env python3
"""Generate Greedy native dependency notices from the locked Cargo graph."""

import argparse
import json
from pathlib import Path
import re
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
CRATE = ROOT / 'exes/greedy'
OUTPUTS = (
    CRATE / 'THIRD_PARTY_NOTICES.md',
    ROOT / 'packages/greedy/THIRD_PARTY_NOTICES.md',
)
TARGETS = (
    'aarch64-apple-darwin',
    'x86_64-pc-windows-msvc',
    'x86_64-unknown-linux-gnu',
)
MIT_MARKER = 'Permission is hereby granted, free of charge'
APACHE_MARKERS = ('Apache License', 'Version 2.0, January 2004')


def cargo_metadata():
    result = subprocess.run(
        [
            'cargo',
            'metadata',
            '--locked',
            '--format-version',
            '1',
        ],
        cwd=CRATE,
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(result.stdout)


def cargo_tree(target):
    result = subprocess.run(
        [
            'cargo',
            'tree',
            '--locked',
            # CI sets CARGO_TERM_COLOR=always, and a repeated subtree's "(*)" marker then
            # arrives wrapped in ANSI escapes that the line parser below cannot read.
            '--color',
            'never',
            '-p',
            'greedy-rs',
            '--target',
            target,
            '--edges',
            'normal',
            '--prefix',
            'none',
            '--format',
            '{p}',
        ],
        cwd=CRATE,
        check=True,
        capture_output=True,
        text=True,
    )
    packages = set()
    for line in result.stdout.splitlines():
        match = re.match(r'^(\S+) v(\S+)(?: \(.+\))?$', line)
        if not match:
            raise ValueError(f'Cannot parse cargo tree package line: {line!r}')
        packages.add(match.groups())
    return packages


def package_closure():
    metadata = cargo_metadata()
    by_name_version = {}
    for package in metadata['packages']:
        key = (package['name'], package['version'])
        by_name_version.setdefault(key, []).append(package)
    closure = set()
    for target in TARGETS:
        closure.update(cargo_tree(target))
    packages = []
    for key in sorted(closure):
        matches = by_name_version.get(key, [])
        if len(matches) != 1:
            raise ValueError(f'Expected one metadata package for {key}, found {len(matches)}')
        if matches[0]['source'] is not None:
            packages.append(matches[0])
    return packages


def license_files(package):
    package_dir = Path(package['manifest_path']).parent
    return sorted(
        path
        for path in package_dir.iterdir()
        if path.is_file() and re.match(r'^(licen[cs]e|copying)', path.name, re.IGNORECASE)
    )


def matching_license(package, license_name):
    files = license_files(package)
    if license_name == 'MIT':
        preferred = ('LICENSE-MIT', 'LICENSE-MIT.md', 'LICENSE.md', 'LICENSE')
        marker = lambda text: MIT_MARKER in text
    elif license_name == 'Apache-2.0':
        preferred = ('LICENSE-APACHE', 'LICENSE-APACHE.md', 'LICENSE.md', 'LICENSE')
        marker = lambda text: all(value in text for value in APACHE_MARKERS)
    else:
        raise ValueError(f'Unsupported license choice {license_name}')

    order = {name: index for index, name in enumerate(preferred)}
    files.sort(key=lambda path: (order.get(path.name, len(order)), path.name))
    for path in files:
        text = path.read_text(encoding='utf8').strip()
        if marker(text):
            return path.name, text
    raise FileNotFoundError(
        f"{package['name']} {package['version']} permits {license_name}, "
        'but its cached crate has no matching license text'
    )


def selected_license(package):
    expression = package.get('license') or ''
    alternatives = [item.strip() for item in expression.split(' OR ')]
    if 'MIT' in alternatives:
        license_name = 'MIT'
    elif 'Apache-2.0' in alternatives:
        license_name = 'Apache-2.0'
    else:
        raise ValueError(
            f"{package['name']} {package['version']} has unsupported license expression "
            f'{expression!r}; review it before distribution'
        )
    filename, text = matching_license(package, license_name)
    return license_name, filename, text


def render():
    sections = [
        '# Greedy third-party notices',
        '',
        'Generated by `python scripts/greedy-third-party-notices.py` from the',
        'locked normal dependency closure of the Greedy native CLI for Linux x64,',
        'Windows x64, and Apple ARM. Do not edit this file by hand.',
    ]
    for package in package_closure():
        license_name, filename, license_text = selected_license(package)
        sections.extend([
            '',
            f"## {package['name']} {package['version']}",
            '',
            f"Declared license: `{package['license']}`",
            '',
            f'Selected license: `{license_name}` from `{filename}`',
        ])
        if package.get('repository'):
            sections.extend(['', f"Repository: {package['repository']}"])
        if package.get('authors'):
            sections.extend(['', 'Authors: ' + '; '.join(package['authors'])])
        sections.extend(['', '```text', license_text, '```'])
    return '\n'.join(sections) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    content = render()
    if args.check:
        stale = [path for path in OUTPUTS if not path.exists() or path.read_text(encoding='utf8') != content]
        if stale:
            for path in stale:
                print(f'Out of date: {path.relative_to(ROOT)}', file=sys.stderr)
            return 1
        print(f'Verified {len(OUTPUTS)} Greedy third-party notice files')
        return 0
    for path in OUTPUTS:
        path.write_text(content, encoding='utf8')
        print(path.relative_to(ROOT))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
